services:
  laravel-docker:
    container_name: ispmanager-docker
    build: .
    volumes:
      - ./ispmanager-app:/var/www/html
    ports:
      - 80:80

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: P46e6qR4H8bHo5tk
      MYSQL_DATABASE: dk_imdb
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
